package moonee.ee;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import moonee.mod_EE;
import moonee.ee.items.ItemAeternalisFuel;
import moonee.ee.items.ItemAlchemicalCoal;
import moonee.ee.items.ItemAlchemyBag;
import moonee.ee.items.ItemAlchemyTome;
import moonee.ee.items.ItemArcaneRing;
import moonee.ee.items.ItemAttractionRing;
import moonee.ee.items.ItemBaseRing;
import moonee.ee.items.ItemBodyStone;
import moonee.ee.items.ItemCatalystStone;
import moonee.ee.items.ItemCovalenceDust;
import moonee.ee.items.ItemDarkAxe;
import moonee.ee.items.ItemDarkHammer;
import moonee.ee.items.ItemDarkHoe;
import moonee.ee.items.ItemDarkMatter;
import moonee.ee.items.ItemDarkMatterArmor;
import moonee.ee.items.ItemDarkMatterBoots;
import moonee.ee.items.ItemDarkMatterGreaves;
import moonee.ee.items.ItemDarkMatterHelmet;
import moonee.ee.items.ItemDarkPickaxe;
import moonee.ee.items.ItemDarkShears;
import moonee.ee.items.ItemDarkSpade;
import moonee.ee.items.ItemDarkSword;
import moonee.ee.items.ItemDiviningRod;
import moonee.ee.items.ItemEternamDensity;
import moonee.ee.items.ItemEvertide;
import moonee.ee.items.ItemGrimarchRing;
import moonee.ee.items.ItemHarvestRing;
import moonee.ee.items.ItemHyperCatalyst;
import moonee.ee.items.ItemHyperKineticLens;
import moonee.ee.items.ItemIgnitionRing;
import moonee.ee.items.ItemKlienStar1;
import moonee.ee.items.ItemKlienStar2;
import moonee.ee.items.ItemKlienStar3;
import moonee.ee.items.ItemKlienStar4;
import moonee.ee.items.ItemKlienStar5;
import moonee.ee.items.ItemKlienStar6;
import moonee.ee.items.ItemLifeStone;
import moonee.ee.items.ItemLootBall;
import moonee.ee.items.ItemMercurialEye;
import moonee.ee.items.ItemMindStone;
import moonee.ee.items.ItemMobiusFuel;
import moonee.ee.items.ItemPhilStone;
import moonee.ee.items.ItemRedAxe;
import moonee.ee.items.ItemRedHammer;
import moonee.ee.items.ItemRedHoe;
import moonee.ee.items.ItemRedKatar;
import moonee.ee.items.ItemRedMace;
import moonee.ee.items.ItemRedMatter;
import moonee.ee.items.ItemRedMatterArmor;
import moonee.ee.items.ItemRedMatterArmorP;
import moonee.ee.items.ItemRedMatterBoots;
import moonee.ee.items.ItemRedMatterBootsP;
import moonee.ee.items.ItemRedMatterGreaves;
import moonee.ee.items.ItemRedMatterGreavesP;
import moonee.ee.items.ItemRedMatterHelmet;
import moonee.ee.items.ItemRedMatterHelmetP;
import moonee.ee.items.ItemRedPickAxe;
import moonee.ee.items.ItemRedShears;
import moonee.ee.items.ItemRedSpade;
import moonee.ee.items.ItemRedSword;
import moonee.ee.items.ItemRepairCharm;
import moonee.ee.items.ItemSoulStone;
import moonee.ee.items.ItemSwiftWolfRing;
import moonee.ee.items.ItemTransTablet;
import moonee.ee.items.ItemVoidRing;
import moonee.ee.items.ItemVolcanite;
import moonee.ee.items.ItemWatchOfTime;
import moonee.ee.items.ItemZeroRing;
import net.minecraft.item.Item;

public class EEItem {

	public static Item philStone;
	public static Item catalystStone;
	public static Item baseRing;
	public static Item attractionRing;
	public static Item grimarchRing;
	public static Item harvestRing;
	public static Item ignitionRing;
	public static Item swiftWolfRing;
	public static Item zeroRing;
	public static Item evertide;
	public static Item volcanite;
	public static Item hyperkineticLens;
	public static Item eternalDensity;
	public static Item watchOfTime;
	public static Item darkMatter;
	public static Item darkPickaxe;
	public static Item darkSpade;
	public static Item darkSword;
	public static Item darkAxe;
	public static Item darkHoe;
	public static Item darkShears;
	public static Item darkHammer;
	public static Item repairCharm;
	public static Item darkMatterArmor;
	public static Item darkMatterBoots;
	public static Item darkMatterGreaves;
	public static Item darkMatterHelmet;
	public static Item alchemicalCoal;
	public static Item mobiusFuel;
	public static Item aeternalisFuel;
	public static Item covalenceDust;
	public static Item kleinStar1;
	public static Item kleinStar2;
	public static Item kleinStar3;
	public static Item kleinStar4;
	public static Item kleinStar5;
	public static Item kleinStar6;
	public static Item alchemyBag;
	public static Item redPickaxe;
	public static Item redSpade;
	public static Item redSword;
	public static Item redAxe;
	public static Item redHoe;
	public static Item redShears;
	public static Item redHammer;
	public static Item redKatar;
	public static Item redMace;
	public static Item hyperCatalyst;
	public static Item redMatter;
	public static Item diviningRod;
	public static Item mercurialEye;
	public static Item transTablet;
	public static Item redMatterArmor;
	public static Item redMatterBoots;
	public static Item redMatterGreaves;
	public static Item redMatterHelmet;
	public static Item redMatterArmorP;
	public static Item redMatterBootsP;
	public static Item redMatterGreavesP;
	public static Item redMatterHelmetP;
	public static Item bodyStone;
	public static Item soulStone;
	public static Item lifeStone;
	public static Item mindStone;
	public static Item arcaneRing;
	public static Item voidRing;
	public static Item alchemyTome;
	public static Item lootBall;

	public static void init() {
		
		System.out.println("==== Moon's EE: Loading Items! ====");
		
		Item philStone = new ItemPhilStone(2013).setItemName("PhilStone").setIconIndex(0).setCreativeTab(mod_EE.EEtab);
		Item catalystStone = new ItemCatalystStone(2014).setItemName("catalystStone").setIconIndex(1).setCreativeTab(mod_EE.EEtab);
		Item baseRing = new ItemBaseRing(2015).setItemName("baseRing").setIconIndex(2).setCreativeTab(mod_EE.EEtab);
		Item attractionRing = new ItemAttractionRing(2016).setItemName("attractionRing").setIconIndex(3).setCreativeTab(mod_EE.EEtab);
		Item grimarchRing = new ItemGrimarchRing(2017).setItemName("grimarchRing").setIconIndex(5).setCreativeTab(mod_EE.EEtab);
		Item harvestRing = new ItemHarvestRing(2018).setItemName("harvestRing").setIconIndex(6).setCreativeTab(mod_EE.EEtab);
		Item ignitionRing = new ItemIgnitionRing(2019).setItemName("ignitionRing").setIconIndex(8).setCreativeTab(mod_EE.EEtab);
		Item swiftWolfRing = new ItemSwiftWolfRing(2020).setItemName("swiftWolfRing").setIconIndex(10).setCreativeTab(mod_EE.EEtab);
		Item zeroRing = new ItemZeroRing(2021).setItemName("zeroRing").setIconIndex(14).setCreativeTab(mod_EE.EEtab);
		Item evertide = new ItemEvertide(2022).setItemName("evertide").setIconIndex(16).setCreativeTab(mod_EE.EEtab);
		Item volcanite = new ItemVolcanite(2023).setItemName("volcanite").setIconIndex(17).setCreativeTab(mod_EE.EEtab);
		Item hyperkineticLens = new ItemHyperKineticLens(2024).setItemName("hyperkineticLens").setIconIndex(18).setCreativeTab(mod_EE.EEtab);
		Item eternalDensity = new ItemEternamDensity(2025).setItemName("eternalDensity").setIconIndex(19).setCreativeTab(mod_EE.EEtab);	
		Item watchOfTime = new ItemWatchOfTime(2027).setItemName("watchOfTime").setIconIndex(21).setCreativeTab(mod_EE.EEtab);
		
		
		
		
		
		Item darkMatter = new ItemDarkMatter(2028).setItemName("darkMatter").setIconIndex(23).setCreativeTab(mod_EE.EEtab);
		Item darkPickaxe = new ItemDarkPickaxe(2029).setItemName("darkPickaxe").setIconIndex(24).setCreativeTab(mod_EE.EEtab);
		Item darkSpade = new ItemDarkSpade(2030).setItemName("darkSpade").setIconIndex(25).setCreativeTab(mod_EE.EEtab);
		Item darkSword = new ItemDarkSword(2031).setItemName("darkSword").setIconIndex(26).setCreativeTab(mod_EE.EEtab);
		Item darkAxe = new ItemDarkAxe(2032).setItemName("darkAxe").setIconIndex(27).setCreativeTab(mod_EE.EEtab);
		Item darkHoe = new ItemDarkHoe(2033).setItemName("darkHoe").setIconIndex(28).setCreativeTab(mod_EE.EEtab);
		Item darkShears = new ItemDarkShears(2034).setItemName("darkShears").setIconIndex(29).setCreativeTab(mod_EE.EEtab);
		Item darkHammer = new ItemDarkHammer(2035).setItemName("darkHammer").setIconIndex(30).setCreativeTab(mod_EE.EEtab);
		Item repairCharm = new ItemRepairCharm(2036).setItemName("repairCharm").setIconIndex(31).setCreativeTab(mod_EE.EEtab);
		Item darkMatterArmor = new ItemDarkMatterArmor(2037).setItemName("darkMatterArmor").setIconIndex(32).setCreativeTab(mod_EE.EEtab);
		Item darkMatterBoots = new ItemDarkMatterBoots(2038).setItemName("darkMatterBoots").setIconIndex(33).setCreativeTab(mod_EE.EEtab);
		Item darkMatterGreaves = new ItemDarkMatterGreaves(2039).setItemName("darkMatterGreaves").setIconIndex(34).setCreativeTab(mod_EE.EEtab);
		Item darkMatterHelmet = new ItemDarkMatterHelmet(2040).setItemName("darkMatterHelmet").setIconIndex(35).setCreativeTab(mod_EE.EEtab);
		Item alchemicalCoal = new ItemAlchemicalCoal(2041).setItemName("alchemicalCoal").setIconIndex(36).setCreativeTab(mod_EE.EEtab);
		Item mobiusFuel = new ItemMobiusFuel(2042).setItemName("mobiusFuel").setIconIndex(37).setCreativeTab(mod_EE.EEtab);
		Item aeternalisFuel = new ItemAeternalisFuel(2043).setItemName("aeternalisFuel").setIconIndex(38).setCreativeTab(mod_EE.EEtab);
		Item covalenceDust = new ItemCovalenceDust(2044).setItemName("covalenceDust").setIconIndex(39).setCreativeTab(mod_EE.EEtab);
		Item kleinStar1 = new ItemKlienStar1(2045).setItemName("kleinStar1").setIconIndex(42).setCreativeTab(mod_EE.EEtab);
		Item kleinStar2 = new ItemKlienStar2(2046).setItemName("kleinStar2").setIconIndex(43).setCreativeTab(mod_EE.EEtab);
		Item kleinStar3 = new ItemKlienStar3(2047).setItemName("kleinStar3").setIconIndex(44).setCreativeTab(mod_EE.EEtab);
		Item kleinStar4 = new ItemKlienStar4(2048).setItemName("kleinStar4").setIconIndex(45).setCreativeTab(mod_EE.EEtab);
		Item kleinStar5 = new ItemKlienStar5(2049).setItemName("kleinStar5").setIconIndex(46).setCreativeTab(mod_EE.EEtab);
		Item kleinStar6 = new ItemKlienStar6(2050).setItemName("kleinStar6").setIconIndex(47).setCreativeTab(mod_EE.EEtab);
		Item alchemyBag = new ItemAlchemyBag(2051).setItemName("alchemyBag").setIconIndex(48).setCreativeTab(mod_EE.EEtab);
		Item redPickaxe = new ItemRedPickAxe(2052).setItemName("redPickaxe").setIconIndex(64).setCreativeTab(mod_EE.EEtab);
		Item redSpade = new ItemRedSpade(2053).setItemName("redSpade").setIconIndex(65).setCreativeTab(mod_EE.EEtab);
		Item redSword = new ItemRedSword(2054).setItemName("redSword").setIconIndex(66).setCreativeTab(mod_EE.EEtab);
		Item redAxe = new ItemRedAxe(2055).setItemName("redAxe").setIconIndex(67).setCreativeTab(mod_EE.EEtab);
		Item redHoe = new ItemRedHoe(2056).setItemName("redHoe").setIconIndex(68).setCreativeTab(mod_EE.EEtab);
		Item redShears = new ItemRedShears(2057).setItemName("redShears").setIconIndex(69).setCreativeTab(mod_EE.EEtab);
		Item redHammer = new ItemRedHammer(2058).setItemName("redHammer").setIconIndex(70).setCreativeTab(mod_EE.EEtab);
		Item redKatar = new ItemRedKatar(2059).setItemName("redKatar").setIconIndex(71).setCreativeTab(mod_EE.EEtab);
		Item redMace = new ItemRedMace(2060).setItemName("redMace").setIconIndex(72).setCreativeTab(mod_EE.EEtab);
		Item hyperCatalyst = new ItemHyperCatalyst(2061).setItemName("hyperCatalyst").setIconIndex(73).setCreativeTab(mod_EE.EEtab);
		Item redMatter = new ItemRedMatter(2062).setItemName("redMatter").setIconIndex(74).setCreativeTab(mod_EE.EEtab);
		Item diviningRod = new ItemDiviningRod(2063).setItemName("diviningRod").setIconIndex(75).setCreativeTab(mod_EE.EEtab);
		Item mercurialEye = new ItemMercurialEye(2064).setItemName("mercurialEye").setIconIndex(78).setCreativeTab(mod_EE.EEtab);
		Item transTablet = new ItemTransTablet(2065).setItemName("transTablet").setIconIndex(79).setCreativeTab(mod_EE.EEtab);
		Item redMatterArmor = new ItemRedMatterArmor(2066).setItemName("redMatterArmor").setIconIndex(80).setCreativeTab(mod_EE.EEtab);
		Item redMatterBoots = new ItemRedMatterBoots(2067).setItemName("redMatterBoots").setIconIndex(81).setCreativeTab(mod_EE.EEtab);
		Item redMatterGreaves = new ItemRedMatterGreaves(2068).setItemName("redMatterGreaves").setIconIndex(82).setCreativeTab(mod_EE.EEtab);
		Item redMatterHelmet = new ItemRedMatterHelmet(2069).setItemName("redMatterHelmet").setIconIndex(83).setCreativeTab(mod_EE.EEtab);
		Item redMatterArmorP = new ItemRedMatterArmorP(2070).setItemName("redMatterArmorP").setIconIndex(84).setCreativeTab(mod_EE.EEtab);
		Item redMatterBootsP = new ItemRedMatterBootsP(2071).setItemName("redMatterBootsP").setIconIndex(85).setCreativeTab(mod_EE.EEtab);
		Item redMatterGreavesP = new ItemRedMatterGreavesP(2072).setItemName("redMatterGreavesP").setIconIndex(86).setCreativeTab(mod_EE.EEtab);
		Item redMatterHelmetP = new ItemRedMatterHelmetP(2073).setItemName("redMatterHelmetP").setIconIndex(87).setCreativeTab(mod_EE.EEtab);
		Item bodyStone = new ItemBodyStone(2074).setItemName("bodyStone").setIconIndex(88).setCreativeTab(mod_EE.EEtab);
		Item soulStone = new ItemSoulStone(2075).setItemName("soulStone").setIconIndex(90).setCreativeTab(mod_EE.EEtab);
		Item lifeStone = new ItemLifeStone(2076).setItemName("lifeStone").setIconIndex(92).setCreativeTab(mod_EE.EEtab);
		Item mindStone = new ItemMindStone(2077).setItemName("mindStone").setIconIndex(94).setCreativeTab(mod_EE.EEtab);
		Item arcaneRing = new ItemArcaneRing(2078).setItemName("arcaneRing").setIconIndex(96).setCreativeTab(mod_EE.EEtab);
		Item voidRing = new ItemVoidRing(2079).setItemName("voidRing").setIconIndex(3).setCreativeTab(mod_EE.EEtab);
		Item alchemyTome = new ItemAlchemyTome(2080).setItemName("alchemyTome").setIconIndex(106).setCreativeTab(mod_EE.EEtab);
		Item lootBall = new ItemLootBall(2081).setItemName("lootBall").setIconIndex(107).setCreativeTab(mod_EE.EEtab);
	
		LanguageRegistry.addName(watchOfTime, "Watch Of Time");
		LanguageRegistry.addName(darkMatter, "Dark Matter");
		LanguageRegistry.addName(darkPickaxe, "Dark Matter Pickaxe");
		LanguageRegistry.addName(darkSpade, "Dark Matter Shovel");
		LanguageRegistry.addName(darkSword, "Dark Matter Sword");
		LanguageRegistry.addName(darkAxe, "Dark Matter Axe");
		LanguageRegistry.addName(darkShears, "Dark Matter Shears");
		LanguageRegistry.addName(darkHoe, "Dark Matter Hoe");
		LanguageRegistry.addName(darkHammer, "Dark Matter Hammer");
		LanguageRegistry.addName(repairCharm, "Talisman of Repair");
		LanguageRegistry.addName(darkMatterArmor, "Dark Matter Amor");
		LanguageRegistry.addName(darkMatterBoots, "Dark Matter Boots");
		LanguageRegistry.addName(darkMatterGreaves, "Dark Matter Pants");
		LanguageRegistry.addName(darkMatterHelmet, "Dark Matter Helmet");
		LanguageRegistry.addName(mobiusFuel, "Mobius Fuel");
		LanguageRegistry.addName(covalenceDust, "Covalence Dust");
		LanguageRegistry.addName(alchemicalCoal, "Alchemical Coal");
		LanguageRegistry.addName(aeternalisFuel, "Aeternalis Fuel");
		LanguageRegistry.addName(kleinStar1, "Klein Star Ein");
		LanguageRegistry.addName(kleinStar2, "Klein Star Zwei");
		LanguageRegistry.addName(kleinStar3, "Klein Star Drei");
		LanguageRegistry.addName(kleinStar4, "Klein Star Vier");
		LanguageRegistry.addName(kleinStar5, "Klein Star Sphere");
		LanguageRegistry.addName(kleinStar6, "Klein Star Omega");
		LanguageRegistry.addName(alchemyBag, "Alchemy Bag");
		LanguageRegistry.addName(redPickaxe, "Red Matter Pickaxe");
		LanguageRegistry.addName(redSword, "Red Matter Sword");
		LanguageRegistry.addName(redSpade, "Red Matter Spade");
		LanguageRegistry.addName(redHoe, "Red Matter Hoe");
		LanguageRegistry.addName(redAxe, "Red Matter Axe");
		LanguageRegistry.addName(redShears, "Red Matter Shears");
		LanguageRegistry.addName(redHammer, "Red Matter Hammer");
		LanguageRegistry.addName(redKatar, "Red Matter Katar");
		LanguageRegistry.addName(redMace, "Morningstar");
		LanguageRegistry.addName(hyperCatalyst, "Hyper Catalyst");
		LanguageRegistry.addName(redMatter, "Red Matter");
		LanguageRegistry.addName(diviningRod, "Divining Rod");
		LanguageRegistry.addName(mercurialEye, "Mercurial Eye");
		LanguageRegistry.addName(transTablet, "Transmutation Tablet");
		LanguageRegistry.addName(redMatterArmor, "Red Matter Armor");
		LanguageRegistry.addName(redMatterBoots, "Red Matter Boots");
		LanguageRegistry.addName(redMatterGreaves, "Red Matter Pants");
		LanguageRegistry.addName(lootBall, "Loot Ball");
		LanguageRegistry.addName(voidRing, "Void Ring");
		LanguageRegistry.addName(arcaneRing, "Arcane Ring");
		LanguageRegistry.addName(zeroRing, "Zero Ring");
		LanguageRegistry.addName(mindStone, "Mind Stone");
		LanguageRegistry.addName(lifeStone, "Life Stone");
		LanguageRegistry.addName(redMatterHelmet, "Red Matter Helmet");
		LanguageRegistry.addName(soulStone, "Soul Stone");
		LanguageRegistry.addName(redMatterGreavesP, "Gravity Pants");
		LanguageRegistry.addName(bodyStone, "Body Stone");
		LanguageRegistry.addName(redMatterHelmetP, "Abyss Helmet");
		LanguageRegistry.addName(redMatterBootsP, "Hurricane Boots");
		LanguageRegistry.addName(redMatterArmorP, "Infernal Armor");
		LanguageRegistry.addName(alchemyTome, "Alchemy Tome");
		LanguageRegistry.addName(evertide, "Evertide Amulet");
		LanguageRegistry.addName(volcanite, "Volcanite Amulet");
		LanguageRegistry.addName(hyperkineticLens, "Hyperkinetic Lens");
		LanguageRegistry.addName(eternalDensity, "Gem of Eternal Density");
		LanguageRegistry.addName(baseRing, "Iron Band");
		LanguageRegistry.addName(attractionRing, "Black Hole Band");
		LanguageRegistry.addName(grimarchRing, "Archangel's Smite");
		LanguageRegistry.addName(harvestRing, "Harvest Goddess Band");
		LanguageRegistry.addName(ignitionRing, "Ring Of Ignition");
		LanguageRegistry.addName(swiftWolfRing, "Swiftwolf's Rending Gale");
		LanguageRegistry.addName(catalystStone, "Destruction Catalyst");
		LanguageRegistry.addName(philStone, "Philosopher's Stone");
		
		GameRegistry.registerItem(watchOfTime, "Watch Of Time");
		GameRegistry.registerItem(darkMatter, "Dark Matter");
		GameRegistry.registerItem(darkPickaxe, "Dark Matter Pickaxe");
		GameRegistry.registerItem(darkSpade, "Dark Matter Shovel");
		GameRegistry.registerItem(darkSword, "Dark Matter Sword");
		GameRegistry.registerItem(darkAxe, "Dark Matter Axe");
		GameRegistry.registerItem(darkShears, "Dark Matter Shears");
		GameRegistry.registerItem(darkHoe, "Dark Matter Hoe");
		GameRegistry.registerItem(darkHammer, "Dark Matter Hammer");
		GameRegistry.registerItem(repairCharm, "Talisman of Repair");
		GameRegistry.registerItem(darkMatterArmor, "Dark Matter Amor");
		GameRegistry.registerItem(darkMatterBoots, "Dark Matter Boots");
		GameRegistry.registerItem(darkMatterGreaves, "Dark Matter Pants");
		GameRegistry.registerItem(darkMatterHelmet, "Dark Matter Helmet");
		GameRegistry.registerItem(mobiusFuel, "Mobius Fuel");
		GameRegistry.registerItem(covalenceDust, "Covalence Dust");
		GameRegistry.registerItem(alchemicalCoal, "Alchemical Coal");
		GameRegistry.registerItem(aeternalisFuel, "Aeternalis Fuel");
		GameRegistry.registerItem(kleinStar1, "Klein Star Ein");
		GameRegistry.registerItem(kleinStar2, "Klein Star Zwei");
		GameRegistry.registerItem(kleinStar3, "Klein Star Drei");
		GameRegistry.registerItem(kleinStar4, "Klein Star Vier");
		GameRegistry.registerItem(kleinStar5, "Klein Star Sphere");
		GameRegistry.registerItem(kleinStar6, "Klein Star Omega");
		GameRegistry.registerItem(alchemyBag, "Alchemy Bag");
		GameRegistry.registerItem(redPickaxe, "Red Matter Pickaxe");
		GameRegistry.registerItem(redSword, "Red Matter Sword");
		GameRegistry.registerItem(redSpade, "Red Matter Spade");
		GameRegistry.registerItem(redHoe, "Red Matter Hoe");
		GameRegistry.registerItem(redAxe, "Red Matter Axe");
		GameRegistry.registerItem(redShears, "Red Matter Shears");
		GameRegistry.registerItem(redHammer, "Red Matter Hammer");
		GameRegistry.registerItem(redKatar, "Red Matter Katar");
		GameRegistry.registerItem(redMace, "Morningstar");
		GameRegistry.registerItem(hyperCatalyst, "Hyper Catalyst");
		GameRegistry.registerItem(redMatter, "Red Matter");
		GameRegistry.registerItem(diviningRod, "Divining Rod");
		GameRegistry.registerItem(mercurialEye, "Mercurial Eye");
		GameRegistry.registerItem(transTablet, "Transmutation Tablet");
		GameRegistry.registerItem(redMatterArmor, "Red Matter Armor");
		GameRegistry.registerItem(redMatterBoots, "Red Matter Boots");
		GameRegistry.registerItem(redMatterGreaves, "Red Matter Pants");
		GameRegistry.registerItem(lootBall, "Loot Ball");
		GameRegistry.registerItem(voidRing, "Void Ring");
		GameRegistry.registerItem(arcaneRing, "Arcane Ring");
		GameRegistry.registerItem(zeroRing, "Zero Ring");
		GameRegistry.registerItem(mindStone, "Mind Stone");
		GameRegistry.registerItem(lifeStone, "Life Stone");
		GameRegistry.registerItem(redMatterHelmet, "Red Matter Helmet");
		GameRegistry.registerItem(soulStone, "Soul Stone");
		GameRegistry.registerItem(redMatterGreavesP, "Gravity Pants");
		GameRegistry.registerItem(bodyStone, "Body Stone");
		GameRegistry.registerItem(redMatterHelmetP, "Abyss Helmet");
		GameRegistry.registerItem(redMatterBootsP, "Hurricane Boots");
		GameRegistry.registerItem(redMatterArmorP, "Infernal Armor");
		GameRegistry.registerItem(alchemyTome, "Alchemy Tome");
		GameRegistry.registerItem(evertide, "Evertide Amulet");
		GameRegistry.registerItem(volcanite, "Volcanite Amulet");
		GameRegistry.registerItem(hyperkineticLens, "Hyperkinetic Lens");
		GameRegistry.registerItem(eternalDensity, "Gem of Eternal Density");
		GameRegistry.registerItem(baseRing, "Iron Band");
		GameRegistry.registerItem(attractionRing, "Black Hole Band");
		GameRegistry.registerItem(grimarchRing, "Archangel's Smite");
		GameRegistry.registerItem(harvestRing, "Harvest Goddess Band");
		GameRegistry.registerItem(ignitionRing, "Ring Of Ignition");
		GameRegistry.registerItem(swiftWolfRing, "Swiftwolf's Rending Gale");
		GameRegistry.registerItem(catalystStone, "Destruction Catalyst");
		GameRegistry.registerItem(philStone, "Philosopher's Stone");

	}

}
